import {createElement} from 'react';
export const Deck = props => createElement('deck', props);
export const Slide = props => createElement('slide', props);
export const Model = props => createElement('model', props);
export const Animate = props => createElement('animate', props);
export const Computer = props => createElement('computer', props);
export const CommandLine = props => createElement('commandline', props);
export const Scalar = props => createElement('scalar', props);
export const Image = props => createElement('image', props);
export const Exchange = props => createElement('exchange', props);
export const SpeedGraph = props => createElement('speedgraph', props);
